lib: [
  "_build/install/default/lib/tezos-data-encoding/META" {"META"}
  "_build/install/default/lib/tezos-data-encoding/opam" {"opam"}
  "_build/install/default/lib/tezos-data-encoding/tezos_data_encoding__Data_encoding.cmi"
  "_build/install/default/lib/tezos-data-encoding/tezos_data_encoding__Data_encoding.cmx"
  "_build/install/default/lib/tezos-data-encoding/tezos_data_encoding__Data_encoding.cmt"
  "_build/install/default/lib/tezos-data-encoding/tezos_data_encoding__Data_encoding.cmti"
  "_build/install/default/lib/tezos-data-encoding/data_encoding.mli"
  "_build/install/default/lib/tezos-data-encoding/tezos_data_encoding__Hex_encode.cmi"
  "_build/install/default/lib/tezos-data-encoding/tezos_data_encoding__Hex_encode.cmx"
  "_build/install/default/lib/tezos-data-encoding/tezos_data_encoding__Hex_encode.cmt"
  "_build/install/default/lib/tezos-data-encoding/tezos_data_encoding__Hex_encode.cmti"
  "_build/install/default/lib/tezos-data-encoding/hex_encode.mli"
  "_build/install/default/lib/tezos-data-encoding/tezos_data_encoding.cmi"
  "_build/install/default/lib/tezos-data-encoding/tezos_data_encoding.cmx"
  "_build/install/default/lib/tezos-data-encoding/tezos_data_encoding.cmt"
  "_build/install/default/lib/tezos-data-encoding/tezos_data_encoding.ml-gen"
  "_build/install/default/lib/tezos-data-encoding/tezos_data_encoding.cma"
  "_build/install/default/lib/tezos-data-encoding/tezos_data_encoding.cmxa"
  "_build/install/default/lib/tezos-data-encoding/tezos_data_encoding.a"
  "_build/install/default/lib/tezos-data-encoding/tezos_data_encoding.cmxs"
]
doc: [
  "_build/install/default/doc/tezos-data-encoding/README.md"
  "_build/install/default/doc/tezos-data-encoding/CHANGES.alphanet"
]
