#! /usr/bin/env bash

## from genesis to demo

set -e

test_dir="$(cd "$(dirname "$0")" && echo "$(pwd -P)")"
source $test_dir/test_lib.inc.sh "$@"

start_node 1

show_logs="no"

sleep 2

# autogenerated from the demo source
protocol_version="PsxS1brZfzzXCiFwirbMtQr4X5XR6SiHQ46HajpFDdk9GBXR6vy"

$admin_client inject protocol "$test_dir/demo"
$admin_client list protocols
$client activate protocol $protocol_version with fitness 1 and key dictator and parameters $parameters_file
answ=$($client -p ProtoALphaALph rpc post /blocks/head/protocol with {} 2>/dev/null)

if ! grep "$protocol_version" <<< $answ ; then
  exit 1
fi

echo
echo End of test
echo
