(**************************************************************************)
(*                                                                        *)
(*    Copyright (c) 2014 - 2017.                                          *)
(*    Dynamic Ledger Solutions, Inc. <contact@tezos.com>                  *)
(*                                                                        *)
(*    All rights reserved. No warranty, explicit or implicit, provided.   *)
(*                                                                        *)
(**************************************************************************)

(* Where all the user friendliness starts *)
let () = Pervasives.exit (Lwt_main.run (
    Main_lib.main ~only_commands:(Client_debug.commands ()
                                  @ Client_admin.commands ()
                                  @ Client_network.commands ()
                                  @ Client_generic_rpcs.commands) ()))
