FROM $base_image

COPY src tezos/src
COPY test tezos/test
COPY scripts tezos/scripts
COPY Makefile jbuild .ocp-indent tezos/

RUN sudo chown -R opam /home/opam/tezos && \
    cd tezos && \
    opam config exec -- make all && \
    opam config exec -- make build-test
