FROM $base_image

COPY scripts/install_build_deps.sh scripts/version.sh scripts/
COPY src/tezos-deps.opam src/
RUN sudo apk update && \
    opam config exec -- ./scripts/install_build_deps.sh all && \
    sudo rm -f /var/cache/apk/* && \
    rm -fr ~/.opam/log/ && \
    rm -fr "$(opam config exec -- ocamlfind query stdlib)"/topdirs.cmi
