FROM alpine:$alpine_version

LABEL distro_style="apk" distro="alpine" distro_long="alpine-$alpine_version" arch="x86_64" operatingsystem="linux"

RUN apk update && \
    apk upgrade && \
    apk add sudo bash libssl1.0 libsodium gmp git && \
    rm -f /var/cache/apk/* && \
    adduser -S tezos && \
    echo 'tezos ALL=(ALL:ALL) NOPASSWD:ALL' > /etc/sudoers.d/tezos && \
    chmod 440 /etc/sudoers.d/tezos && \
    chown root:root /etc/sudoers.d/tezos && \
    sed -i 's/^Defaults.*requiretty//g' /etc/sudoers
USER tezos

COPY . /home/tezos
WORKDIR /home/tezos

RUN sudo chown root:root bin/* && \
    sudo chmod a+rx bin/* && \
    sudo mv bin/* /usr/local/bin && \
    rmdir bin

ENTRYPOINT [ "/bin/bash" ]
