
SOURCE_DIRECTORIES += baker

CLIENT_INTFS += \
  baker/client_mining_blocks.mli \
  baker/client_mining_operations.mli \
  baker/client_mining_endorsement.mli \
  baker/client_mining_denunciation.mli \
  baker/client_mining_revelation.mli \
  baker/client_mining_forge.mli \
  baker/client_mining_daemon.mli \
  baker/client_mining_main.mli \

CLIENT_IMPLS += \
  baker/client_mining_blocks.ml \
  baker/client_mining_operations.ml \
  baker/client_mining_endorsement.ml \
  baker/client_mining_denunciation.ml \
  baker/client_mining_revelation.ml \
  baker/client_mining_forge.ml \
  baker/client_mining_daemon.ml \
  baker/client_mining_main.ml \

