
SOURCE_DIRECTORIES += mining

INTFS += \
  mining/client_mining_blocks.mli \
  mining/client_mining_operations.mli \
  mining/client_mining_endorsement.mli \
  mining/client_mining_denunciation.mli \
  mining/client_mining_revelation.mli \
  mining/client_mining_forge.mli \
  mining/client_mining_daemon.mli \
  mining/client_mining_main.mli \

IMPLS += \
  mining/client_mining_blocks.ml \
  mining/client_mining_operations.ml \
  mining/client_mining_endorsement.ml \
  mining/client_mining_denunciation.ml \
  mining/client_mining_revelation.ml \
  mining/client_mining_forge.ml \
  mining/client_mining_daemon.ml \
  mining/client_mining_main.ml \

