
INCLUDES = \
  $(patsubst %, -I %, $(SOURCE_DIRECTORIES)) \
  $(patsubst %, -package %, $(PACKAGES)) \
  $(patsubst %, -open %, $(OPENED_MODULES))

OCAMLFLAGS = \
  -g -safe-string -bin-annot -w +27-30-40 -short-paths \
  ${INCLUDES} \
  ${EXTRA_OCAMLFLAGS}

OCAMLC = ocamlfind ocamlc
OCAMLOPT = ocamlfind ocamlopt
OCAMLMKTOP = ocamlfind ocamlmktop
OCAMLDEP = ocamlfind ocamldep
OCAMLRES = ocp-ocamlres
OCAMLLEX = ocamllex
MENHIR = menhir
