
ifeq ($(strip ${COVERAGE}),yes)
  COVERAGEPKG := bisect_ppx
endif

INCLUDES = \
  $(patsubst %, -I %, $(SOURCE_DIRECTORIES)) \
  $(patsubst %, -package %, $(PACKAGES)) \
  $(patsubst %, -open %, $(OPENED_MODULES))

ifneq ($(strip ${PRODUCTION}),yes)
DEVFLAGS := -bin-annot -g
endif

OCAMLFLAGS = \
  ${DEVFLAGS} -thread -short-paths -safe-string -w +27-30-40@8 \
  ${INCLUDES} \
  ${EXTRA_OCAMLFLAGS}

UTOPFLAGS = $(filter-out -thread,${OCAMLFLAGS})

OCAMLC = ocamlfind ocamlc
OCAMLOPT = ocamlfind ocamlopt
OCAMLMKTOP = ocamlfind ocamlmktop
OCAMLDEP = ocamlfind ocamldep
OCAMLRES = ocp-ocamlres
OCAMLLEX = ocamllex
MENHIR = menhir
