lib: [
  "_build/install/default/lib/tezos-base/META" {"META"}
  "_build/install/default/lib/tezos-base/opam" {"opam"}
  "_build/install/default/lib/tezos-base/tezos_base__MBytes.cmi"
  "_build/install/default/lib/tezos-base/tezos_base__MBytes.cmx"
  "_build/install/default/lib/tezos-base/tezos_base__MBytes.cmt"
  "_build/install/default/lib/tezos-base/tezos_base__MBytes.cmti"
  "_build/install/default/lib/tezos-base/mBytes.mli"
  "_build/install/default/lib/tezos-base/tezos_base.cmi"
  "_build/install/default/lib/tezos-base/tezos_base.cmx"
  "_build/install/default/lib/tezos-base/tezos_base.cmt"
  "_build/install/default/lib/tezos-base/tezos_base.ml-gen"
  "_build/install/default/lib/tezos-base/tezos_base__Utils.cmi"
  "_build/install/default/lib/tezos-base/tezos_base__Utils.cmx"
  "_build/install/default/lib/tezos-base/tezos_base__Utils.cmt"
  "_build/install/default/lib/tezos-base/tezos_base__Utils.cmti"
  "_build/install/default/lib/tezos-base/utils.mli"
  "_build/install/default/lib/tezos-base/tezos_base.cma"
  "_build/install/default/lib/tezos-base/tezos_base.cmxa"
  "_build/install/default/lib/tezos-base/tezos_base.a"
  "_build/install/default/lib/tezos-base/tezos_base.cmxs"
]
libexec: [
  "_build/install/default/lib/tezos-base/test-ocp-indent.sh" {"test-ocp-indent.sh"}
]
doc: [
  "_build/install/default/doc/tezos-base/README.md"
  "_build/install/default/doc/tezos-base/CHANGES.alphanet"
]
